server:
  port: 8080
spring:
  mvc:
    servlet:
      path: /garage/api/v1
  datasource:
    url: jdbc:h2:mem:garage-db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /garage/h2-console